name: food_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.1
  http: ^1.2.2
  intl: ^0.18.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^3.0.5
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  introduction_screen: ^3.1.14
  date_field: ^5.3.0
  flutter_html: ^3.0.0-beta.2
  multi_dropdown: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^5.0.0
  # flutter_widget_from_html: ^0.15.3
  syncfusion_flutter_charts: ^27.2.5
  html: ^0.15.4
  async: ^2.11.0
  font_awesome_flutter: ^10.8.0
  animated_splash_screen: ^1.3.0
  quickalert: ^1.1.0
  badges: ^3.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/animation/
    - assets/lottie/
    - assets/lang/

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
